[project]
name = "lessons"
version = "1.0.0"
description = "Lessons from Javacode"
authors = [
    {name = "Sergey"}
]
dependencies = [
    "ruff>=0.9.7",
]
requires-python = ">=3.8"


[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
